package com.mycompany.kristell.DAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mycompany.kristell.DAO.Transaction;
import com.mycompany.kristell.DAO.Card;

import com.mycompany.kristell.DAO.TransactionDao;
import com.mycompany.kristell.DAO.CardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig transactionDaoConfig;
    private final DaoConfig cardDaoConfig;

    private final TransactionDao transactionDao;
    private final CardDao cardDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        transactionDaoConfig = daoConfigMap.get(TransactionDao.class).clone();
        transactionDaoConfig.initIdentityScope(type);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        transactionDao = new TransactionDao(transactionDaoConfig, this);
        cardDao = new CardDao(cardDaoConfig, this);

        registerDao(Transaction.class, transactionDao);
        registerDao(Card.class, cardDao);
    }
    
    public void clear() {
        transactionDaoConfig.getIdentityScope().clear();
        cardDaoConfig.getIdentityScope().clear();
    }

    public TransactionDao getTransactionDao() {
        return transactionDao;
    }

    public CardDao getCardDao() {
        return cardDao;
    }

}
