package com.mycompany.kristell.DAO;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.mycompany.kristell.DAO.Transaction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSACTION".
*/
public class TransactionDao extends AbstractDao<Transaction, Long> {

    public static final String TABLENAME = "TRANSACTION";

    /**
     * Properties of entity Transaction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Amount = new Property(1, Double.class, "Amount", false, "AMOUNT");
        public final static Property OccurredTime = new Property(2, java.util.Date.class, "OccurredTime", false, "OCCURRED_TIME");
        public final static Property Comments = new Property(3, String.class, "Comments", false, "COMMENTS");
        public final static Property CardId = new Property(4, Long.class, "CardId", false, "CARD_ID");
    };

    private DaoSession daoSession;

    private Query<Transaction> card_TransactionListQuery;

    public TransactionDao(DaoConfig config) {
        super(config);
    }
    
    public TransactionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSACTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"AMOUNT\" REAL," + // 1: Amount
                "\"OCCURRED_TIME\" INTEGER," + // 2: OccurredTime
                "\"COMMENTS\" TEXT," + // 3: Comments
                "\"CARD_ID\" INTEGER);"); // 4: CardId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSACTION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Transaction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double Amount = entity.getAmount();
        if (Amount != null) {
            stmt.bindDouble(2, Amount);
        }
 
        java.util.Date OccurredTime = entity.getOccurredTime();
        if (OccurredTime != null) {
            stmt.bindLong(3, OccurredTime.getTime());
        }
 
        String Comments = entity.getComments();
        if (Comments != null) {
            stmt.bindString(4, Comments);
        }
 
        Long CardId = entity.getCardId();
        if (CardId != null) {
            stmt.bindLong(5, CardId);
        }
    }

    @Override
    protected void attachEntity(Transaction entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Transaction readEntity(Cursor cursor, int offset) {
        Transaction entity = new Transaction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // Amount
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // OccurredTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Comments
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // CardId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Transaction entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAmount(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setOccurredTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setComments(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCardId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Transaction entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Transaction entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "transactionList" to-many relationship of Card. */
    public List<Transaction> _queryCard_TransactionList(Long CardId) {
        synchronized (this) {
            if (card_TransactionListQuery == null) {
                QueryBuilder<Transaction> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CardId.eq(null));
                card_TransactionListQuery = queryBuilder.build();
            }
        }
        Query<Transaction> query = card_TransactionListQuery.forCurrentThread();
        query.setParameter(0, CardId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCardDao().getAllColumns());
            builder.append(" FROM TRANSACTION T");
            builder.append(" LEFT JOIN CARD T0 ON T.\"CARD_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Transaction loadCurrentDeep(Cursor cursor, boolean lock) {
        Transaction entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Card card = loadCurrentOther(daoSession.getCardDao(), cursor, offset);
        entity.setCard(card);

        return entity;    
    }

    public Transaction loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Transaction> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Transaction> list = new ArrayList<Transaction>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Transaction> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Transaction> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
